meta:
  title: Joe Webber / Tech & Product Leader
  title_template: %s / Joe Webber
  author: Joe Webber

site:
  origin: https://joewebber.co.uk
  view_transitions: true

rss:
  enabled: true
  title: Joe Webber
  description: Tech & Product Leader
  collection: blog

design:
  inline_css: true

collections:
  blog:
    include: [posts/]
    require: [title]
    sort: date desc
